<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-UUTKFR9P" ignored="0" name="t1" tests="2" failures="1" timestamp="2020-11-20T19:29:14 CST" time="69.152" errors="0">
  <testcase name="demo1" time="22.658" classname="com.webtest.demo.BaseInformation"/>
  <testcase name="demo1" time="42.227" classname="com.webtest.demo.UserSet">
    <failure type="java.lang.ArrayIndexOutOfBoundsException" message="2">
      <![CDATA[java.lang.ArrayIndexOutOfBoundsException: 2
at com.webtest.core.BaseTest.getExcel(Unknown Source)
at com.webtest.demo.UserSet.demo1(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- demo1 -->
</testsuite> <!-- t1 -->
